/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.33
 * Generated at: 2018-12-09 07:32:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class circum_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html lang=\"en\">\n");

	String flag = request.getParameter("logout");
	if(flag != null)	
	{
		session.removeAttribute("userID");
	}

      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <title title=\"circum\">周边</title>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link href=\"./css/circum.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <script src=\"./js/jquery-3.3.1.min.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"./js/bootstrap.min.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"./js/nav.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"js/main.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"./js/circum.js\" type=\"text/javascript\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body onload=\"start()\">\n");
      out.write("    <div id=\"nav\">\n");
      out.write("        <p id=\"username\">\n");
      out.write("            ");
      out.print(session.getAttribute("userID"));
      out.write("\n");
      out.write("        </p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"circum-body row\">\n");
      out.write("        <div class=\"sub-nav\">\n");
      out.write("            <div class=\"btn-group btn-lg\">\n");
      out.write("                <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                    分类<span class=\"glyphicon glyphicon-th-list\"></span>\n");
      out.write("                </button>\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"leftmenu\">\n");
      out.write("                    <li><a href=\"javascript:onclick=setObj.apply(circum,[1])\">景点</a></li>\n");
      out.write("                    <li class=\"divider\"></li>\n");
      out.write("                    <li><a href=\"javascript:onclick=setObj.apply(circum,[2])\">商户</a></li>\n");
      out.write("                    <li class=\"divider\"></li>\n");
      out.write("                    <li><a href=\"javascript:onclick=setObj.apply(circum,[3])\">美食</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"carousel-example-generic\" class=\"carousel slide col-md-8 col-md-offset-1\" data-ride=\"carousel\">\n");
      out.write("            <!-- Indicators -->\n");
      out.write("            <ol class=\"carousel-indicators\">\n");
      out.write("                <li data-target=\"#carousel-example-generic\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("                <li data-target=\"#carousel-example-generic\" data-slide-to=\"1\"></li>\n");
      out.write("                <li data-target=\"#carousel-example-generic\" data-slide-to=\"2\"></li>\n");
      out.write("            </ol>\n");
      out.write("            <div class=\"carousel-inner\" id=\"content\" role=\"listbox\">\n");
      out.write("            </div>\n");
      out.write("            <!-- Controls -->\n");
      out.write("            <a class=\"left carousel-control\" href=\"#carousel-example-generic\" role=\"button\" data-slide=\"prev\">\n");
      out.write("                <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\n");
      out.write("                <span class=\"sr-only\">Previous</span>\n");
      out.write("            </a>\n");
      out.write("            <a class=\"right carousel-control\" href=\"#carousel-example-generic\" role=\"button\" data-slide=\"next\">\n");
      out.write("                <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\n");
      out.write("                <span class=\"sr-only\">Next</span>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <!--login Modal -->\n");
      out.write("        <div class=\"modal fade\" id=\"login-Modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"login-model-lbl\">\n");
      out.write("            <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                            <span aria-hidden=\"true\">&times;</span>\n");
      out.write("                        </button>\n");
      out.write("                        <h4 class=\"modal-title\" id=\"login-model-lbl\">登录</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-md-8\">\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <form method=\"post\" action=\"userLoginServlet\" class=\"form-horizontal\" role=\"form\" id=\"login\">\n");
      out.write("                                        <div class=\"form-group col-md-12\">\n");
      out.write("                                            <div class=\"col-md-3 text-center \">\n");
      out.write("                                                <label for=\"inputUesrName\" class=\"control-label\">账号</label>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-8\">\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"userName\" name=\"userName\" maxlength=\"20\" autofocus=\"\" placeholder=\"请输入账号\" autocomplete=\"on\" />\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group col-md-12\">\n");
      out.write("                                            <div class=\"col-md-3 text-center\">\n");
      out.write("                                                <label for=\"inputPassword\" class=\"control-label\">密码</label>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-8\">\n");
      out.write("                                                <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" maxlength=\"20\" placeholder=\"请输入密码\" autocomplete=\"on\" />\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group col-md-12\">\n");
      out.write("                                            <div class=\"col-md-3\">\n");
      out.write("                                                <label for=\"Code\" class=\"control-label\">验证码</label>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-5\">\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"inputCode\" name=\"inputCode\" maxlength=\"20\" placeholder=\"请输入验证码\" maxlength=\"4\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-2\">\n");
      out.write("                                                <input type=\"button\" class=\"btn\" id=\"code\" onclick=\"createCode()\">\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group col-md-12 text-center\">\n");
      out.write("                                            <a href=\"./register.jsp\">未注册，进入注册页面</a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </form>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-4\">\n");
      out.write("                                <img src=\"src/Logo.png\" class=\"img-responsive\" alt=\"LOGO\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"modal-footer center-block\">\n");
      out.write("                                <input type=\"button\" id=\"btn\" class=\"btn btn-success col-md-4 col-md-offset-2\" name=\"loginsubmit\" value=\"登录\" onclick=\"login()\"> <input type=\"button\" id=\"btn-cancl\" class=\"btn btn-default col-md-4\" value=\"取消\" data-dismiss=\"modal\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
