/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.33
 * Generated at: 2018-11-18 06:57:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class circum_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lan=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title title=\"circum\">周边</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"./css/circum.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <script src=\"./js/jquery-3.3.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"js/mySystem.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"js/main.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./js/circum.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"start()\">\r\n");
      out.write("    <div class=\"circum-nav\">\r\n");
      out.write("        <div class=\"navbar main-navigation navbar-fixed-top navbar-inverse\" role=\"navigation\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#goods-navbar-collapse\">\r\n");
      out.write("                        <span class=\"sr-only\">导航</span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"#\"> <img alt=\"brand\" src=\"./src/LOGO32.ico\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"goods-navbar-collapse\">\r\n");
      out.write("                    <ul class=\" nav navbar-nav\">\r\n");
      out.write("                        <li><a href=\"./on.jsp\">首页</a></li>\r\n");
      out.write("                        <li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> 新闻<b class=\"caret\"></b>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><a onclick=\"pushPassage(this)\">校内公众号推送</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"dropdown\"><a href=\"#\" onclick=\"circum()\"> 周边 </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a hef=\"#\">商户</a></li>\r\n");
      out.write("                        <li class=\"dropdown\"><a clas=\"dropdown-toggle\" data-toggle=\"dropdown\"> 交流<b class=\"caret\"></b>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><a href=\"#\">失物招领</a></li>\r\n");
      out.write("                                <li class=\"divider\"></li>\r\n");
      out.write("                                <li><a href=\"#\">交流</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\">兼职</a></li>\r\n");
      out.write("                        <li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> 学术<b class=\"caret\"></b>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><a href=\"#\">竞赛</a></li>\r\n");
      out.write("                                <li class=\"divider\"></li>\r\n");
      out.write("                                <li><a href=\"#\">科研</a></li>\r\n");
      out.write("                                <li class=\"divider\"></li>\r\n");
      out.write("                                <li><a href=\"#\">讲座</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"navbar-right\">\r\n");
      out.write("                        <div class=\"navbar-left\" id=\"log-button\">\r\n");
      out.write("                            <button class=\"btn navbar-btn btn-success\" data-toggle=\"modal\" data-target=\"#login-Modal\" onclick=\"createCode()\">\r\n");
      out.write("                                <span class=\"glyphicon glyphicon-log-in\"></span> 登录\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a class=\"navbar-text\" id=\"log-status\">\r\n");
      out.write("                            ");
      out.print(session.getAttribute("userID"));
      out.write("\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"navbar-right\">\r\n");
      out.write("                            <form class=\"navbar-form\" action=\"#\" method=\"post\" role=\"search\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"search\" class=\"form-control\" placeholder=\"搜索\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-info\" onclick=\"create()\">搜索</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"circum-body\">\r\n");
      out.write("        <div class=\"sub-nav\">\r\n");
      out.write("            <img src=\"src/LOGO32.ico\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"silder-box silder-box-3\">\r\n");
      out.write("            <div class=\"silder\">\r\n");
      out.write("                <ul id=\"content\">\r\n");
      out.write("                    <!--\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <article id=\"111\" class=\"post\">\r\n");
      out.write("                            <div class=\"post-head\">\r\n");
      out.write("                                <div class=\"post-img\">\r\n");
      out.write("                                    <img src=\"./img/02.png\" class=\"img-rounded img-responsive img-circle\" alt=\"章鱼丸子大公司\" title=\"章鱼丸子大公司\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"post-name\">\r\n");
      out.write("                                    <a href=\"#\" class=\"h2 pull-right\">章鱼丸子</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"post-company text-sm pull-left h4\">\r\n");
      out.write("                                    章鱼丸子大公司\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"post-content\">\r\n");
      out.write("                                <p>1234567894654654654654654654654654ledhfowehtiowehoit</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <footer class=\"post-footer\">\r\n");
      out.write("                                <div class=\"tag-cloud\">\r\n");
      out.write("                                    <a>美味</a>\r\n");
      out.write("                                    <a>小吃</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <address class=\"pull-left\"><strong>地址：</strong>学院路1号</address>\r\n");
      out.write("                            </footer>\r\n");
      out.write("                        </article>\r\n");
      out.write("                    </li>\r\n");
      out.write("-->\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class='silder-button btl'></div>\r\n");
      out.write("            <div class='silder-button btr'></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--login Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"login-Modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"login-model-lbl\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <h4 class=\"modal-title\" id=\"login-model-lbl\">登录</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <form method=\"post\" action=\"userLoginServlet\" class=\"form-horizontal\" role=\"form\" id=\"login\">\r\n");
      out.write("                                    <div class=\"form-group col-md-12\">\r\n");
      out.write("                                        <div class=\"col-md-3 text-center \">\r\n");
      out.write("                                            <label for=\"inputUesrName\" class=\"control-label\">账号</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"userName\" name=\"userName\" maxlength=\"20\" autofocus=\"\" placeholder=\"请输入账号\" autocomplete=\"on\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group col-md-12\">\r\n");
      out.write("                                        <div class=\"col-md-3 text-center\">\r\n");
      out.write("                                            <label for=\"inputPassword\" class=\"control-label\">密码</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8\">\r\n");
      out.write("                                            <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" maxlength=\"20\" placeholder=\"请输入密码\" autocomplete=\"on\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group col-md-12\">\r\n");
      out.write("                                        <div class=\"col-md-3\">\r\n");
      out.write("                                            <label for=\"Code\" class=\"control-label\">验证码</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-5\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"inputCode\" name=\"inputCode\" maxlength=\"20\" placeholder=\"请输入验证码\" maxlength=\"4\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-2\">\r\n");
      out.write("                                            <input type=\"button\" class=\"btn\" id=\"code\" onclick=\"createCode()\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group col-md-12 text-center\">\r\n");
      out.write("                                        <a href=\"./login.jsp\">未注册，进入注册页面</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <img src=\"src/Logo.png\" class=\"img-responsive\" alt=\"LOGO\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"modal-footer center-block\">\r\n");
      out.write("                            <input type=\"button\" id=\"btn\" class=\"btn btn-success col-md-4 col-md-offset-2\" name=\"loginsubmit\" value=\"登录\" onclick=\"login()\"> <input type=\"button\" id=\"btn-cancl\" class=\"btn btn-default col-md-4\" value=\"取消\" data-dismiss=\"modal\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(function() {\r\n");
      out.write("            //回调函数计数\r\n");
      out.write("            var callbackIndex = 0;\r\n");
      out.write("            $('.silder-box-3').mySilder({\r\n");
      out.write("                width: 310, //容器的宽度 必选参数!!!!!!\r\n");
      out.write("                height: 800, //容器的高度 必选参数!!!!!!\r\n");
      out.write("                direction: 'x', //滚动方向,默认X方向\r\n");
      out.write("                few: 1, //一次滚动几个，默认滚动1张\r\n");
      out.write("                showFew: 5, //显示几个,就不用调css了,默认显示一个\r\n");
      out.write("                clearance: 20, //容器之间的间隙，默认为 0\r\n");
      out.write("                silderMode: 'easeInOutCubic', //滚动方式\r\n");
      out.write("                timeGap: 350, //动画间隙，完成一次动画需要多长时间，默认700ms\r\n");
      out.write("                auto: false, //是否自动滚动 \r\n");
      out.write("                autoTime: 5, //自动滚动时，时间间隙，即多长滚动一次\r\n");
      out.write("                buttonPre: '.silder-button.btl', //上一个，按钮\r\n");
      out.write("                buttonNext: '.silder-button.btr', //下一个，按钮\r\n");
      out.write("                jz: true //点击时，是否等待动画完成\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            /*------------------\r\n");
      out.write("            ------------------滚动方式\r\n");
      out.write("            linear swing jswing \r\n");
      out.write("            easeInQuad  easeOutQuad  easeInOutQuad \r\n");
      out.write("            easeInCubic  easeOutCubic  easeInOutCubic \r\n");
      out.write("            easeInQuart  easeOutQuart  easeInOutQuart  \r\n");
      out.write("            easeInQuint  easeOutQuint  easeInOutQuint \r\n");
      out.write("            easeInSine  easeOutSine   easeInOutSine \r\n");
      out.write("            easeInExpo  easeOutExpo  easeInOutExpo \r\n");
      out.write("            easeInCirc  easeOutCirc  easeInOutCirc \r\n");
      out.write("            easeInElastic  easeOutElastic  easeInOutElastic  \r\n");
      out.write("            easeInBack  easeOutBack  easeInOutBack \r\n");
      out.write("            easeInBounce  easeOutBounce  easeInOutBounce\r\n");
      out.write("            ------------------\r\n");
      out.write("            -----------------*/\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
