/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.33
 * Generated at: 2018-10-27 07:18:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>main</title>\r\n");
      out.write("    <script src=\"./js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"./js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"./js/jquery.jSlider.js\"></script>\r\n");
      out.write("    <script src=\"./js/time.js\"></script>\r\n");
      out.write("    <script src=\"./js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link href=\"./css/jSlider.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./css/main-css.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body background=\"./src/paper2.jpg\" style=\"background-repeat:no-repeat;background-size:100% 100%;background-attachment: fixed;\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"navbar main-navigation navbar-default\" role=\"navigation\">\r\n");
      out.write("\t        <div class=\"container\">\r\n");
      out.write("\t        \r\n");
      out.write("\t            <div class=\"navbar-header\">\r\n");
      out.write("\t                <!--<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#goods-navbar-collapse\">\r\n");
      out.write("\t                    <span class=\"sr-only\">导航</span>\r\n");
      out.write("\t                    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t                    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t                    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t                </button>-->\r\n");
      out.write("\t                <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("\t                    <img alt=\"brand\" src=\"./src/Logo1.jpg\">\r\n");
      out.write("\t                </a>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t\r\n");
      out.write("\t            <div class=\"collapse navbar-collapse\" id=\"goods-nacbar-collapse\">\r\n");
      out.write("\t                <div class=\"navbar-collapse collapse\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t            <ul class=\"text-center nav navbar-nav\"  style=\"display: inline-block;float: none;\">\r\n");
      out.write("\t\t\t                <li>\r\n");
      out.write("\t\t\t                    <h4 style=\"font-family:华文楷体; font-weight:bold;\"></h4>\r\n");
      out.write("\t\t\t                </li>\r\n");
      out.write("\t\t\t            </ul>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t            \t<ul class=\"nav navbar-nav pull-right\">\r\n");
      out.write("\t\t                    <li>\r\n");
      out.write("\t\t                        <a href=\"#\">注册</a>\r\n");
      out.write("\t\t                    </li>\r\n");
      out.write("\t\t                </ul>\r\n");
      out.write("\t\t                <ul class=\"nav navbar-nav pull-right\">\r\n");
      out.write("\t\t                    <li>\r\n");
      out.write("\t\t                        <a href=\"#\">登录</a>\r\n");
      out.write("\t\t                    </li>\r\n");
      out.write("\t\t                </ul>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"myCarousel\" class=\"picture_background2 carousel slide\">\r\n");
      out.write("\t\t<!-- 轮播（Carousel）指标 -->\r\n");
      out.write("\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t</ol>   \r\n");
      out.write("\t\t<!-- 轮播（Carousel）项目 -->\r\n");
      out.write("\t\t<div class=\"picture_background2 carousel-inner\">\r\n");
      out.write("\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t\t<img src=\"./src/sky1.jpg\" alt=\"First slide\" class=\"picture_size\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t<img src=\"./src/tree.jpg\" alt=\"Second slide\" class=\"picture_size\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t<img src=\"./src/picture3.jpg\" alt=\"Third slide\" class=\"picture_size\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 轮播（Carousel）导航 -->\r\n");
      out.write("\t\t<a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t<span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t<span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("\t\t\t<span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t<span class=\"sr-only\">Next</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div> \r\n");
      out.write("\t\r\n");
      out.write("\t<!-- <div class=\"picture_background1\">\r\n");
      out.write("\t\t<img src=\"./src/sky1.jpg\" class=\"img-rounded picture_size\">\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!--  \t<div class=\"content_left_size\" style=\"background-color:red\">\r\n");
      out.write("\t\t\t<img src=\"./src/sky1.jpg\" class=\"img-rounded picture_background2\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"content_right_size1\" style=\"background-color:green\">\r\n");
      out.write("\t\t\t\thttps://c.runoob.com/codedemo/3336\r\n");
      out.write("\t\t\t\t<div class=\"content_right_size\" style=\"background-color:yellow\">\r\n");
      out.write("\t\t\t\t<canvas class=\"clocks\" id=\"canvas\" width=\"500\" height=\"500\"></canvas>\r\n");
      out.write("\t\t\t\t<img src=\"./src/sky1.jpg\" class=\"img-rounded picture_background3\" >\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div> -->\r\n");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\t<div class=\"btn_enter\">\r\n");
      out.write("\t\t<input type=\"button\" data-toggle=\"modal\" data-target=\"#login-Modal\" value=\"Enter\" class=\"btn_size btn_font btn btn-success btn-lg\" onclick=\"window.location.href('#')\" style=\"font-family:华文隶书;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"div_center\">\r\n");
      out.write("\t\t<div class=\"picture_down\">\r\n");
      out.write("\t\t\t<img src=\"./src/print.jpg\" class=\"picture_print img-rounded\">\r\n");
      out.write("\t\t\t<h4 style=\"font-family:华文楷体; font-weight:bold;\">软件背景</h4>\r\n");
      out.write("\t\t\t<div class=\"div_center\">基于当代信息碎片众多，信息获取资源繁多的情况下，Goods的出现会大大减轻当代人获取信息的复杂度，且Bootstrap和J2EE的技术支持，能使产品更加简洁方便，打造出一款适合当代人，衷于当代人，并立足于当代人的信息集成服务平台。</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"picture_down\">\r\n");
      out.write("\t\t\t<img src=\"./src/boots.jpg\" class=\"picture_boots img-rounded\">\r\n");
      out.write("\t\t\t<h4 style=\"font-family:华文楷体; font-weight:bold;\">团队介绍</h4>\r\n");
      out.write("\t\t\t<div class=\"div_center\">开发团队具有高素质、高能力、高效率，有一定的项目开发经验，对用户了解深入，熟悉用户使用习惯与心理，能够开发出一款让用户满意的产品。</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"picture_down\">\r\n");
      out.write("\t\t\t<img src=\"./src/mountain.jpg\" class=\"picture_mountain img-rounded\">\r\n");
      out.write("\t\t\t<h4 style=\"font-family:华文楷体; font-weight:bold;\">小组成员</h4>\r\n");
      out.write("\t\t\t<div class=\"div_center\">程俊伟、李锦伦、翁修杰、梁颂伟、何俊泽</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"div_space\"> </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"js/main.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"js/news.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
