/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.33
 * Generated at: 2018-11-30 02:23:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class on_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head lang=\"zh-CN\">\r\n");
      out.write("    <title>On</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <script src=\"js/main.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"js/jquery-3.3.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <link href=\"css/on.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link type=\"text/css\" href=\"css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"ms-windows\">\r\n");
      out.write("    <div class=\"Goods-home\">\r\n");
      out.write("        <!--\r\n");
      out.write("\t\t导航栏\r\n");
      out.write("\t\t<div class=\"navbar-fixed-top navbar-inverse\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("-->\r\n");
      out.write("        <div class=\"Goods-content\">\r\n");
      out.write("            <div class=\"Goods-content-cell-whiteBlock\">\r\n");
      out.write("                <div class=\"Goods-content-cell-whiteBlockcontent\">\r\n");
      out.write("                    <div class=\"whiteBlockcontent-Header\">\r\n");
      out.write("                        <img class=\"imgLogo\" src=\"src/LOGO1.gif\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h1 class=\"whiteBlockcontent-Title\">发现校园周边新鲜事</h1>\r\n");
      out.write("                    <div class=\"whiteBlockcontentform\">\r\n");
      out.write("                        <h2 class=\"whiteBlockcontentTitle\">现在就加入Goods。</h2>\r\n");
      out.write("                        <div class=\"buttons\">\r\n");
      out.write("                            <a class=\"EdgeButton EdgeButton-primary  EdgeButton-buttonRegister a-decoration\" href=\"javascript:location.href='register.jsp'\">注册</a>\r\n");
      out.write("                            <a class=\"EdgeButton EdgeButton-secondary EdgeButton-buttonLogin a-decoration\" href=\"javascript:location.href='index.jsp?logout=exit'\" onclick=\"setCookie('flag', false, 1)\">登录</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"Goods-content-cell-blueBlock\">\r\n");
      out.write("                <div class=\"Goods-content-cell-blueBlockcontent\">\r\n");
      out.write("                    <div class=\"Goods-content-cell-blueBlockcontent-item\">\r\n");
      out.write("                        <span class=\"Icon fa fa-search\">\r\n");
      out.write("                        </span>关注你的兴趣所在。\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"Goods-content-cell-blueBlockcontent-item\">\r\n");
      out.write("                        <span class=\"Icon fa fa-comment-o\">\r\n");
      out.write("                        </span>畅谈身边趣事。\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"Goods-content-cell-blueBlockcontent-item\">\r\n");
      out.write("                        <span class=\"Icon fa fa-home\">\r\n");
      out.write("                        </span>丰富大学生活。\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"Goods-footer Goods-footer-fixed\">\r\n");
      out.write("            <ul class=\"Goods-footer-list\">\r\n");
      out.write("                <li class=\"Goods-footer-item\">\r\n");
      out.write("                    <a class=\"a-style\" href=\"#\" rel=\"noopener\">关于</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"Goods-footer-item\">\r\n");
      out.write("                    <a class=\"a-style\" href=\"#\" rel=\"noopener\">帮助中心</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"Goods-footer-item\">\r\n");
      out.write("                    <a class=\"a-style\" href=\"http://baidu.com\" rel=\"noopener\">百度</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"Goods-footer-item\">\r\n");
      out.write("                    <a class=\"a-style\" href=\"#\" rel=\"noopener\">广告</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"Goods-footer-item\">\r\n");
      out.write("                    <a class=\"a-style\" href=\"#\" rel=\"noopener\">开发者</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"Goods-footer-item Goods-footer-coryright\">© 2018 Goods</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
